# Generated by Django 2.2.28 on 2023-04-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_newmo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.BigIntegerField()),
            ],
        ),
    ]
